// USER AUTH
export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_ADMIN = 'SET_ADMIN'

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUET'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

// SIGN UP
export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST'
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE'

export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO'
export const RECEIVE_USER_FAILURE = 'RECEIVE_USER_FAILURE'
export const RECEIVE_USER_SUCCESS = 'RECEIVE_USER_SUCCESS'

export const SET_ACCESS_LEVEL = 'SET_ACCESS_LEVEL'
export const SET_MONGO_ID = 'SET_MONGO_ID'

// BUILDS
export const GET_BUILDS_REQUEST = 'GET_BUILDS_REQUEST'
export const GET_BUILDS_SUCCESS = 'GET_BUILDS_SUCCESS'
export const GET_BUILDS_FAILURE = 'GET_BUILDS_FAILURE'

export const GET_BUILD_DETAILS_REQUEST = 'GET_BUILD_DETAILS_REQUEST'
export const GET_BUILD_DETAILS_SUCCESS = 'GET_BUILD_DETAILS_SUCCESS'
export const GET_BUILD_DETAILS_FAILURE = 'GET_BUILD_DETAILS_FAILURE'

export const CREATE_BUILD_REQUEST = 'CREATE_BUILD_REQUEST'
export const CREATE_BUILD_SUCCESS = 'CREATE_BUILD_SUCCESS'
export const CREATE_BUILD_FAILURE = 'CREATE_BUILD_FAILURE'

export const DELETE_BUILD_REQUEST = 'DELETE_BUILD_REQUEST'
export const DELETE_BUILD_SUCCESS = 'DELETE_BUILD_SUCCESS'
export const DELETE_BUILD_FAILURE = 'DELETE_BUILD_FAILURE'

// PARTS
export const ADD_PART_REQUEST = 'ADD_PART_REQUEST'
export const ADD_PART_SUCCESS = 'ADD_PART_SUCCESS'
export const ADD_PART_FAILURE = 'ADD_PART_FAILURE'

export const GET_PARTS_REQUEST = 'GET_PARTS_REQUEST'
export const GET_PARTS_SUCCESS = 'GET_PARTS_SUCCESS'
export const GET_PARTS_FAILURE = 'GET_PARTS_FAILURE'

// POSTS
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

export const GET_POST_DETAILS_REQUEST = 'GET_POST_DETAILS_REQUEST'
export const GET_POST_DETAILS_SUCCESS = 'GET_POST_DETAILS_SUCCESS'
export const GET_POST_DETAILS_FAILURE = 'GET_POST_DETAILS_FAILURE'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

export const GET_POST_COMMENTS_REQUEST = "GET_POST_COMMENTS_REQUEST"
export const GET_POST_COMMENTS_SUCCESS = "GET_POST_COMMENTS_SUCCESS"
export const GET_POST_COMMENTS_FAILURE = "GET_POST_COMMENTS_FAILURE"

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE"
