// USER AUTH
export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_ADMIN = 'SET_ADMIN'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST'
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE'

// BUILDS
export const GET_BUILDS_REQUEST = 'GET_BUILDS_REQUEST'
export const GET_BUILDS_SUCCESS = 'GET_BUILDS_SUCCESS'
export const GET_BUILDS_FAILURE = 'GET_BUILDS_FAILURE'
export const GET_BUILD_DETAILS_REQUEST = 'GET_BUILD_DETAILS_REQUEST'
export const GET_BUILD_DETAILS_SUCCESS = 'GET_BUILD_DETAILS_SUCCESS'
export const GET_BUILD_DETAILS_FAILURE = 'GET_BUILD_DETAILS_FAILURE'

